import { z } from 'zod';
export declare const CrmContactSchema: z.ZodObject<{
    id: z.ZodString;
    type: z.ZodDefault<z.ZodEnum<["investor", "producer", "partner", "vendor", "legal", "internal", "other"]>>;
    email: z.ZodString;
    first_name: z.ZodString;
    last_name: z.ZodString;
    title: z.ZodOptional<z.ZodString>;
    company_id: z.ZodOptional<z.ZodString>;
    tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    phone: z.ZodOptional<z.ZodString>;
    whatsapp: z.ZodOptional<z.ZodString>;
    telegram: z.ZodOptional<z.ZodString>;
    source: z.ZodDefault<z.ZodEnum<["referral", "conference", "outbound", "inbound", "partner", "whatsapp", "other"]>>;
    preferred_channel: z.ZodDefault<z.ZodEnum<["whatsapp", "email", "platform", "call"]>>;
    status: z.ZodDefault<z.ZodEnum<["active", "inactive", "do-not-contact", "unsubscribed"]>>;
    created_at: z.ZodString;
    last_contact_at: z.ZodOptional<z.ZodString>;
    notes: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    email: string;
    type: "legal" | "other" | "investor" | "producer" | "partner" | "vendor" | "internal";
    status: "active" | "inactive" | "do-not-contact" | "unsubscribed";
    id: string;
    first_name: string;
    last_name: string;
    tags: string[];
    source: "other" | "whatsapp" | "partner" | "outbound" | "inbound" | "referral" | "conference";
    preferred_channel: "email" | "call" | "whatsapp" | "platform";
    created_at: string;
    title?: string | undefined;
    whatsapp?: string | undefined;
    notes?: string | undefined;
    company_id?: string | undefined;
    phone?: string | undefined;
    telegram?: string | undefined;
    last_contact_at?: string | undefined;
}, {
    email: string;
    id: string;
    first_name: string;
    last_name: string;
    created_at: string;
    type?: "legal" | "other" | "investor" | "producer" | "partner" | "vendor" | "internal" | undefined;
    status?: "active" | "inactive" | "do-not-contact" | "unsubscribed" | undefined;
    title?: string | undefined;
    whatsapp?: string | undefined;
    notes?: string | undefined;
    company_id?: string | undefined;
    tags?: string[] | undefined;
    phone?: string | undefined;
    telegram?: string | undefined;
    source?: "other" | "whatsapp" | "partner" | "outbound" | "inbound" | "referral" | "conference" | undefined;
    preferred_channel?: "email" | "call" | "whatsapp" | "platform" | undefined;
    last_contact_at?: string | undefined;
}>;
export declare const CrmCompanySchema: z.ZodObject<{
    id: z.ZodString;
    name: z.ZodString;
    domain: z.ZodOptional<z.ZodString>;
    industry: z.ZodOptional<z.ZodString>;
    size: z.ZodOptional<z.ZodEnum<["1-10", "11-50", "51-200", "201-500", "501-1000", "1000+"]>>;
    jurisdiction: z.ZodOptional<z.ZodString>;
    website: z.ZodOptional<z.ZodString>;
    linkedin: z.ZodOptional<z.ZodString>;
    tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    type: z.ZodDefault<z.ZodEnum<["investor", "vendor", "partner", "customer", "legal", "prospect", "other"]>>;
    status: z.ZodDefault<z.ZodEnum<["active", "inactive", "blacklisted"]>>;
    created_at: z.ZodString;
    notes: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    type: "legal" | "other" | "investor" | "partner" | "vendor" | "customer" | "prospect";
    name: string;
    status: "active" | "inactive" | "blacklisted";
    id: string;
    tags: string[];
    created_at: string;
    jurisdiction?: string | undefined;
    notes?: string | undefined;
    domain?: string | undefined;
    industry?: string | undefined;
    size?: "1-10" | "11-50" | "51-200" | "201-500" | "501-1000" | "1000+" | undefined;
    website?: string | undefined;
    linkedin?: string | undefined;
}, {
    name: string;
    id: string;
    created_at: string;
    type?: "legal" | "other" | "investor" | "partner" | "vendor" | "customer" | "prospect" | undefined;
    jurisdiction?: string | undefined;
    status?: "active" | "inactive" | "blacklisted" | undefined;
    notes?: string | undefined;
    tags?: string[] | undefined;
    domain?: string | undefined;
    industry?: string | undefined;
    size?: "1-10" | "11-50" | "51-200" | "201-500" | "501-1000" | "1000+" | undefined;
    website?: string | undefined;
    linkedin?: string | undefined;
}>;
export declare const CrmInteractionSchema: z.ZodObject<{
    id: z.ZodString;
    contact_id: z.ZodString;
    company_id: z.ZodOptional<z.ZodString>;
    type: z.ZodEnum<["email", "whatsapp", "call", "meeting", "conference", "demo", "proposal", "contract", "other"]>;
    direction: z.ZodDefault<z.ZodEnum<["inbound", "outbound"]>>;
    subject: z.ZodString;
    summary: z.ZodOptional<z.ZodString>;
    date: z.ZodString;
    duration_minutes: z.ZodOptional<z.ZodNumber>;
    outcome: z.ZodOptional<z.ZodEnum<["positive", "neutral", "negative", "no-response", "follow-up", "closed"]>>;
    follow_up_date: z.ZodOptional<z.ZodString>;
    follow_up_action: z.ZodOptional<z.ZodString>;
    related_deal_id: z.ZodOptional<z.ZodString>;
    email_id: z.ZodOptional<z.ZodString>;
    created_by: z.ZodDefault<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    type: "email" | "call" | "other" | "whatsapp" | "meeting" | "conference" | "demo" | "proposal" | "contract";
    date: string;
    subject: string;
    id: string;
    contact_id: string;
    direction: "outbound" | "inbound";
    created_by: string;
    company_id?: string | undefined;
    summary?: string | undefined;
    duration_minutes?: number | undefined;
    outcome?: "closed" | "positive" | "follow-up" | "neutral" | "negative" | "no-response" | undefined;
    follow_up_date?: string | undefined;
    follow_up_action?: string | undefined;
    related_deal_id?: string | undefined;
    email_id?: string | undefined;
}, {
    type: "email" | "call" | "other" | "whatsapp" | "meeting" | "conference" | "demo" | "proposal" | "contract";
    date: string;
    subject: string;
    id: string;
    contact_id: string;
    company_id?: string | undefined;
    direction?: "outbound" | "inbound" | undefined;
    summary?: string | undefined;
    duration_minutes?: number | undefined;
    outcome?: "closed" | "positive" | "follow-up" | "neutral" | "negative" | "no-response" | undefined;
    follow_up_date?: string | undefined;
    follow_up_action?: string | undefined;
    related_deal_id?: string | undefined;
    email_id?: string | undefined;
    created_by?: string | undefined;
}>;
export declare const CrmRegistrySchema: z.ZodObject<{
    version: z.ZodString;
    last_updated: z.ZodString;
    contacts: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        type: z.ZodDefault<z.ZodEnum<["investor", "producer", "partner", "vendor", "legal", "internal", "other"]>>;
        email: z.ZodString;
        first_name: z.ZodString;
        last_name: z.ZodString;
        title: z.ZodOptional<z.ZodString>;
        company_id: z.ZodOptional<z.ZodString>;
        tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        phone: z.ZodOptional<z.ZodString>;
        whatsapp: z.ZodOptional<z.ZodString>;
        telegram: z.ZodOptional<z.ZodString>;
        source: z.ZodDefault<z.ZodEnum<["referral", "conference", "outbound", "inbound", "partner", "whatsapp", "other"]>>;
        preferred_channel: z.ZodDefault<z.ZodEnum<["whatsapp", "email", "platform", "call"]>>;
        status: z.ZodDefault<z.ZodEnum<["active", "inactive", "do-not-contact", "unsubscribed"]>>;
        created_at: z.ZodString;
        last_contact_at: z.ZodOptional<z.ZodString>;
        notes: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        email: string;
        type: "legal" | "other" | "investor" | "producer" | "partner" | "vendor" | "internal";
        status: "active" | "inactive" | "do-not-contact" | "unsubscribed";
        id: string;
        first_name: string;
        last_name: string;
        tags: string[];
        source: "other" | "whatsapp" | "partner" | "outbound" | "inbound" | "referral" | "conference";
        preferred_channel: "email" | "call" | "whatsapp" | "platform";
        created_at: string;
        title?: string | undefined;
        whatsapp?: string | undefined;
        notes?: string | undefined;
        company_id?: string | undefined;
        phone?: string | undefined;
        telegram?: string | undefined;
        last_contact_at?: string | undefined;
    }, {
        email: string;
        id: string;
        first_name: string;
        last_name: string;
        created_at: string;
        type?: "legal" | "other" | "investor" | "producer" | "partner" | "vendor" | "internal" | undefined;
        status?: "active" | "inactive" | "do-not-contact" | "unsubscribed" | undefined;
        title?: string | undefined;
        whatsapp?: string | undefined;
        notes?: string | undefined;
        company_id?: string | undefined;
        tags?: string[] | undefined;
        phone?: string | undefined;
        telegram?: string | undefined;
        source?: "other" | "whatsapp" | "partner" | "outbound" | "inbound" | "referral" | "conference" | undefined;
        preferred_channel?: "email" | "call" | "whatsapp" | "platform" | undefined;
        last_contact_at?: string | undefined;
    }>, "many">;
    companies: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        name: z.ZodString;
        domain: z.ZodOptional<z.ZodString>;
        industry: z.ZodOptional<z.ZodString>;
        size: z.ZodOptional<z.ZodEnum<["1-10", "11-50", "51-200", "201-500", "501-1000", "1000+"]>>;
        jurisdiction: z.ZodOptional<z.ZodString>;
        website: z.ZodOptional<z.ZodString>;
        linkedin: z.ZodOptional<z.ZodString>;
        tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        type: z.ZodDefault<z.ZodEnum<["investor", "vendor", "partner", "customer", "legal", "prospect", "other"]>>;
        status: z.ZodDefault<z.ZodEnum<["active", "inactive", "blacklisted"]>>;
        created_at: z.ZodString;
        notes: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        type: "legal" | "other" | "investor" | "partner" | "vendor" | "customer" | "prospect";
        name: string;
        status: "active" | "inactive" | "blacklisted";
        id: string;
        tags: string[];
        created_at: string;
        jurisdiction?: string | undefined;
        notes?: string | undefined;
        domain?: string | undefined;
        industry?: string | undefined;
        size?: "1-10" | "11-50" | "51-200" | "201-500" | "501-1000" | "1000+" | undefined;
        website?: string | undefined;
        linkedin?: string | undefined;
    }, {
        name: string;
        id: string;
        created_at: string;
        type?: "legal" | "other" | "investor" | "partner" | "vendor" | "customer" | "prospect" | undefined;
        jurisdiction?: string | undefined;
        status?: "active" | "inactive" | "blacklisted" | undefined;
        notes?: string | undefined;
        tags?: string[] | undefined;
        domain?: string | undefined;
        industry?: string | undefined;
        size?: "1-10" | "11-50" | "51-200" | "201-500" | "501-1000" | "1000+" | undefined;
        website?: string | undefined;
        linkedin?: string | undefined;
    }>, "many">;
    interactions: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        contact_id: z.ZodString;
        company_id: z.ZodOptional<z.ZodString>;
        type: z.ZodEnum<["email", "whatsapp", "call", "meeting", "conference", "demo", "proposal", "contract", "other"]>;
        direction: z.ZodDefault<z.ZodEnum<["inbound", "outbound"]>>;
        subject: z.ZodString;
        summary: z.ZodOptional<z.ZodString>;
        date: z.ZodString;
        duration_minutes: z.ZodOptional<z.ZodNumber>;
        outcome: z.ZodOptional<z.ZodEnum<["positive", "neutral", "negative", "no-response", "follow-up", "closed"]>>;
        follow_up_date: z.ZodOptional<z.ZodString>;
        follow_up_action: z.ZodOptional<z.ZodString>;
        related_deal_id: z.ZodOptional<z.ZodString>;
        email_id: z.ZodOptional<z.ZodString>;
        created_by: z.ZodDefault<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        type: "email" | "call" | "other" | "whatsapp" | "meeting" | "conference" | "demo" | "proposal" | "contract";
        date: string;
        subject: string;
        id: string;
        contact_id: string;
        direction: "outbound" | "inbound";
        created_by: string;
        company_id?: string | undefined;
        summary?: string | undefined;
        duration_minutes?: number | undefined;
        outcome?: "closed" | "positive" | "follow-up" | "neutral" | "negative" | "no-response" | undefined;
        follow_up_date?: string | undefined;
        follow_up_action?: string | undefined;
        related_deal_id?: string | undefined;
        email_id?: string | undefined;
    }, {
        type: "email" | "call" | "other" | "whatsapp" | "meeting" | "conference" | "demo" | "proposal" | "contract";
        date: string;
        subject: string;
        id: string;
        contact_id: string;
        company_id?: string | undefined;
        direction?: "outbound" | "inbound" | undefined;
        summary?: string | undefined;
        duration_minutes?: number | undefined;
        outcome?: "closed" | "positive" | "follow-up" | "neutral" | "negative" | "no-response" | undefined;
        follow_up_date?: string | undefined;
        follow_up_action?: string | undefined;
        related_deal_id?: string | undefined;
        email_id?: string | undefined;
        created_by?: string | undefined;
    }>, "many">;
}, "strip", z.ZodTypeAny, {
    version: string;
    last_updated: string;
    contacts: {
        email: string;
        type: "legal" | "other" | "investor" | "producer" | "partner" | "vendor" | "internal";
        status: "active" | "inactive" | "do-not-contact" | "unsubscribed";
        id: string;
        first_name: string;
        last_name: string;
        tags: string[];
        source: "other" | "whatsapp" | "partner" | "outbound" | "inbound" | "referral" | "conference";
        preferred_channel: "email" | "call" | "whatsapp" | "platform";
        created_at: string;
        title?: string | undefined;
        whatsapp?: string | undefined;
        notes?: string | undefined;
        company_id?: string | undefined;
        phone?: string | undefined;
        telegram?: string | undefined;
        last_contact_at?: string | undefined;
    }[];
    companies: {
        type: "legal" | "other" | "investor" | "partner" | "vendor" | "customer" | "prospect";
        name: string;
        status: "active" | "inactive" | "blacklisted";
        id: string;
        tags: string[];
        created_at: string;
        jurisdiction?: string | undefined;
        notes?: string | undefined;
        domain?: string | undefined;
        industry?: string | undefined;
        size?: "1-10" | "11-50" | "51-200" | "201-500" | "501-1000" | "1000+" | undefined;
        website?: string | undefined;
        linkedin?: string | undefined;
    }[];
    interactions: {
        type: "email" | "call" | "other" | "whatsapp" | "meeting" | "conference" | "demo" | "proposal" | "contract";
        date: string;
        subject: string;
        id: string;
        contact_id: string;
        direction: "outbound" | "inbound";
        created_by: string;
        company_id?: string | undefined;
        summary?: string | undefined;
        duration_minutes?: number | undefined;
        outcome?: "closed" | "positive" | "follow-up" | "neutral" | "negative" | "no-response" | undefined;
        follow_up_date?: string | undefined;
        follow_up_action?: string | undefined;
        related_deal_id?: string | undefined;
        email_id?: string | undefined;
    }[];
}, {
    version: string;
    last_updated: string;
    contacts: {
        email: string;
        id: string;
        first_name: string;
        last_name: string;
        created_at: string;
        type?: "legal" | "other" | "investor" | "producer" | "partner" | "vendor" | "internal" | undefined;
        status?: "active" | "inactive" | "do-not-contact" | "unsubscribed" | undefined;
        title?: string | undefined;
        whatsapp?: string | undefined;
        notes?: string | undefined;
        company_id?: string | undefined;
        tags?: string[] | undefined;
        phone?: string | undefined;
        telegram?: string | undefined;
        source?: "other" | "whatsapp" | "partner" | "outbound" | "inbound" | "referral" | "conference" | undefined;
        preferred_channel?: "email" | "call" | "whatsapp" | "platform" | undefined;
        last_contact_at?: string | undefined;
    }[];
    companies: {
        name: string;
        id: string;
        created_at: string;
        type?: "legal" | "other" | "investor" | "partner" | "vendor" | "customer" | "prospect" | undefined;
        jurisdiction?: string | undefined;
        status?: "active" | "inactive" | "blacklisted" | undefined;
        notes?: string | undefined;
        tags?: string[] | undefined;
        domain?: string | undefined;
        industry?: string | undefined;
        size?: "1-10" | "11-50" | "51-200" | "201-500" | "501-1000" | "1000+" | undefined;
        website?: string | undefined;
        linkedin?: string | undefined;
    }[];
    interactions: {
        type: "email" | "call" | "other" | "whatsapp" | "meeting" | "conference" | "demo" | "proposal" | "contract";
        date: string;
        subject: string;
        id: string;
        contact_id: string;
        company_id?: string | undefined;
        direction?: "outbound" | "inbound" | undefined;
        summary?: string | undefined;
        duration_minutes?: number | undefined;
        outcome?: "closed" | "positive" | "follow-up" | "neutral" | "negative" | "no-response" | undefined;
        follow_up_date?: string | undefined;
        follow_up_action?: string | undefined;
        related_deal_id?: string | undefined;
        email_id?: string | undefined;
        created_by?: string | undefined;
    }[];
}>;
export type CrmContact = z.infer<typeof CrmContactSchema>;
export type CrmCompany = z.infer<typeof CrmCompanySchema>;
export type CrmInteraction = z.infer<typeof CrmInteractionSchema>;
export type CrmRegistry = z.infer<typeof CrmRegistrySchema>;
//# sourceMappingURL=crm.d.ts.map