import { z } from 'zod';
export declare const IpAssetSchema: z.ZodObject<{
    id: z.ZodString;
    type: z.ZodEnum<["patent", "trademark", "trade_secret", "copyright"]>;
    title: z.ZodString;
    status: z.ZodEnum<["draft", "filed", "pending", "registered", "active", "expired", "abandoned"]>;
    jurisdiction: z.ZodString;
    filing_date: z.ZodNullable<z.ZodString>;
    grant_date: z.ZodNullable<z.ZodString>;
    expiry_date: z.ZodNullable<z.ZodString>;
    owner: z.ZodString;
    inventors: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    classes: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
    priority: z.ZodEnum<["critical", "high", "medium", "low"]>;
    next_action: z.ZodString;
    next_action_date: z.ZodString;
}, "strip", z.ZodTypeAny, {
    type: "patent" | "trademark" | "trade_secret" | "copyright";
    jurisdiction: string;
    status: "pending" | "active" | "registered" | "draft" | "expired" | "filed" | "abandoned";
    title: string;
    owner: string;
    id: string;
    next_action: string;
    next_action_date: string;
    filing_date: string | null;
    grant_date: string | null;
    expiry_date: string | null;
    priority: "critical" | "low" | "medium" | "high";
    inventors?: string[] | undefined;
    classes?: string[] | undefined;
}, {
    type: "patent" | "trademark" | "trade_secret" | "copyright";
    jurisdiction: string;
    status: "pending" | "active" | "registered" | "draft" | "expired" | "filed" | "abandoned";
    title: string;
    owner: string;
    id: string;
    next_action: string;
    next_action_date: string;
    filing_date: string | null;
    grant_date: string | null;
    expiry_date: string | null;
    priority: "critical" | "low" | "medium" | "high";
    inventors?: string[] | undefined;
    classes?: string[] | undefined;
}>;
export declare const IpRegistrySchema: z.ZodObject<{
    version: z.ZodString;
    last_updated: z.ZodString;
    assets: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        type: z.ZodEnum<["patent", "trademark", "trade_secret", "copyright"]>;
        title: z.ZodString;
        status: z.ZodEnum<["draft", "filed", "pending", "registered", "active", "expired", "abandoned"]>;
        jurisdiction: z.ZodString;
        filing_date: z.ZodNullable<z.ZodString>;
        grant_date: z.ZodNullable<z.ZodString>;
        expiry_date: z.ZodNullable<z.ZodString>;
        owner: z.ZodString;
        inventors: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
        classes: z.ZodOptional<z.ZodArray<z.ZodString, "many">>;
        priority: z.ZodEnum<["critical", "high", "medium", "low"]>;
        next_action: z.ZodString;
        next_action_date: z.ZodString;
    }, "strip", z.ZodTypeAny, {
        type: "patent" | "trademark" | "trade_secret" | "copyright";
        jurisdiction: string;
        status: "pending" | "active" | "registered" | "draft" | "expired" | "filed" | "abandoned";
        title: string;
        owner: string;
        id: string;
        next_action: string;
        next_action_date: string;
        filing_date: string | null;
        grant_date: string | null;
        expiry_date: string | null;
        priority: "critical" | "low" | "medium" | "high";
        inventors?: string[] | undefined;
        classes?: string[] | undefined;
    }, {
        type: "patent" | "trademark" | "trade_secret" | "copyright";
        jurisdiction: string;
        status: "pending" | "active" | "registered" | "draft" | "expired" | "filed" | "abandoned";
        title: string;
        owner: string;
        id: string;
        next_action: string;
        next_action_date: string;
        filing_date: string | null;
        grant_date: string | null;
        expiry_date: string | null;
        priority: "critical" | "low" | "medium" | "high";
        inventors?: string[] | undefined;
        classes?: string[] | undefined;
    }>, "many">;
}, "strip", z.ZodTypeAny, {
    version: string;
    last_updated: string;
    assets: {
        type: "patent" | "trademark" | "trade_secret" | "copyright";
        jurisdiction: string;
        status: "pending" | "active" | "registered" | "draft" | "expired" | "filed" | "abandoned";
        title: string;
        owner: string;
        id: string;
        next_action: string;
        next_action_date: string;
        filing_date: string | null;
        grant_date: string | null;
        expiry_date: string | null;
        priority: "critical" | "low" | "medium" | "high";
        inventors?: string[] | undefined;
        classes?: string[] | undefined;
    }[];
}, {
    version: string;
    last_updated: string;
    assets: {
        type: "patent" | "trademark" | "trade_secret" | "copyright";
        jurisdiction: string;
        status: "pending" | "active" | "registered" | "draft" | "expired" | "filed" | "abandoned";
        title: string;
        owner: string;
        id: string;
        next_action: string;
        next_action_date: string;
        filing_date: string | null;
        grant_date: string | null;
        expiry_date: string | null;
        priority: "critical" | "low" | "medium" | "high";
        inventors?: string[] | undefined;
        classes?: string[] | undefined;
    }[];
}>;
export type IpAsset = z.infer<typeof IpAssetSchema>;
export type IpRegistry = z.infer<typeof IpRegistrySchema>;
//# sourceMappingURL=ip-asset.d.ts.map