import { z } from 'zod';
/**
 * Unified Communication Thread
 * Aggregates all touchpoints with a contact across Email, WhatsApp, Calendar, CRM
 */
export declare const ThreadMessageSchema: z.ZodObject<{
    id: z.ZodString;
    channel: z.ZodEnum<["email", "whatsapp", "calendar", "call", "meeting", "note"]>;
    direction: z.ZodEnum<["inbound", "outbound"]>;
    timestamp: z.ZodString;
    subject: z.ZodOptional<z.ZodString>;
    body: z.ZodString;
    from: z.ZodString;
    to: z.ZodArray<z.ZodString, "many">;
    status: z.ZodOptional<z.ZodEnum<["sent", "delivered", "read", "failed", "scheduled", "completed"]>>;
    source_id: z.ZodOptional<z.ZodString>;
    metadata: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
}, "strip", z.ZodTypeAny, {
    body: string;
    timestamp: string;
    channel: "email" | "call" | "whatsapp" | "note" | "meeting" | "calendar";
    id: string;
    direction: "outbound" | "inbound";
    to: string[];
    from: string;
    metadata: Record<string, unknown>;
    subject?: string | undefined;
    status?: "sent" | "failed" | "completed" | "delivered" | "scheduled" | "read" | undefined;
    source_id?: string | undefined;
}, {
    body: string;
    timestamp: string;
    channel: "email" | "call" | "whatsapp" | "note" | "meeting" | "calendar";
    id: string;
    direction: "outbound" | "inbound";
    to: string[];
    from: string;
    subject?: string | undefined;
    status?: "sent" | "failed" | "completed" | "delivered" | "scheduled" | "read" | undefined;
    metadata?: Record<string, unknown> | undefined;
    source_id?: string | undefined;
}>;
export declare const ThreadFollowUpSchema: z.ZodObject<{
    id: z.ZodString;
    type: z.ZodEnum<["email", "whatsapp", "call", "meeting"]>;
    scheduled_at: z.ZodString;
    action: z.ZodString;
    status: z.ZodDefault<z.ZodEnum<["pending", "sent", "completed", "cancelled"]>>;
    triggered_by: z.ZodOptional<z.ZodString>;
    auto_trigger: z.ZodDefault<z.ZodBoolean>;
}, "strip", z.ZodTypeAny, {
    type: "email" | "call" | "whatsapp" | "meeting";
    action: string;
    status: "pending" | "sent" | "completed" | "cancelled";
    id: string;
    scheduled_at: string;
    auto_trigger: boolean;
    triggered_by?: string | undefined;
}, {
    type: "email" | "call" | "whatsapp" | "meeting";
    action: string;
    id: string;
    scheduled_at: string;
    status?: "pending" | "sent" | "completed" | "cancelled" | undefined;
    triggered_by?: string | undefined;
    auto_trigger?: boolean | undefined;
}>;
export declare const ThreadSchema: z.ZodObject<{
    id: z.ZodString;
    contact_id: z.ZodString;
    contact_name: z.ZodString;
    contact_email: z.ZodOptional<z.ZodString>;
    contact_whatsapp: z.ZodOptional<z.ZodString>;
    company_id: z.ZodOptional<z.ZodString>;
    company_name: z.ZodOptional<z.ZodString>;
    purpose: z.ZodDefault<z.ZodEnum<["fundraising", "legal", "vendor", "partner", "general"]>>;
    messages: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        channel: z.ZodEnum<["email", "whatsapp", "calendar", "call", "meeting", "note"]>;
        direction: z.ZodEnum<["inbound", "outbound"]>;
        timestamp: z.ZodString;
        subject: z.ZodOptional<z.ZodString>;
        body: z.ZodString;
        from: z.ZodString;
        to: z.ZodArray<z.ZodString, "many">;
        status: z.ZodOptional<z.ZodEnum<["sent", "delivered", "read", "failed", "scheduled", "completed"]>>;
        source_id: z.ZodOptional<z.ZodString>;
        metadata: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
    }, "strip", z.ZodTypeAny, {
        body: string;
        timestamp: string;
        channel: "email" | "call" | "whatsapp" | "note" | "meeting" | "calendar";
        id: string;
        direction: "outbound" | "inbound";
        to: string[];
        from: string;
        metadata: Record<string, unknown>;
        subject?: string | undefined;
        status?: "sent" | "failed" | "completed" | "delivered" | "scheduled" | "read" | undefined;
        source_id?: string | undefined;
    }, {
        body: string;
        timestamp: string;
        channel: "email" | "call" | "whatsapp" | "note" | "meeting" | "calendar";
        id: string;
        direction: "outbound" | "inbound";
        to: string[];
        from: string;
        subject?: string | undefined;
        status?: "sent" | "failed" | "completed" | "delivered" | "scheduled" | "read" | undefined;
        metadata?: Record<string, unknown> | undefined;
        source_id?: string | undefined;
    }>, "many">;
    follow_ups: z.ZodDefault<z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        type: z.ZodEnum<["email", "whatsapp", "call", "meeting"]>;
        scheduled_at: z.ZodString;
        action: z.ZodString;
        status: z.ZodDefault<z.ZodEnum<["pending", "sent", "completed", "cancelled"]>>;
        triggered_by: z.ZodOptional<z.ZodString>;
        auto_trigger: z.ZodDefault<z.ZodBoolean>;
    }, "strip", z.ZodTypeAny, {
        type: "email" | "call" | "whatsapp" | "meeting";
        action: string;
        status: "pending" | "sent" | "completed" | "cancelled";
        id: string;
        scheduled_at: string;
        auto_trigger: boolean;
        triggered_by?: string | undefined;
    }, {
        type: "email" | "call" | "whatsapp" | "meeting";
        action: string;
        id: string;
        scheduled_at: string;
        status?: "pending" | "sent" | "completed" | "cancelled" | undefined;
        triggered_by?: string | undefined;
        auto_trigger?: boolean | undefined;
    }>, "many">>;
    last_activity: z.ZodString;
    last_outbound: z.ZodOptional<z.ZodString>;
    last_inbound: z.ZodOptional<z.ZodString>;
    next_scheduled: z.ZodOptional<z.ZodString>;
    status: z.ZodDefault<z.ZodEnum<["active", "stale", "resolved", "blocked"]>>;
    tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
    clickup_task_id: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    status: "active" | "stale" | "resolved" | "blocked";
    purpose: "legal" | "partner" | "vendor" | "fundraising" | "general";
    id: string;
    tags: string[];
    contact_id: string;
    contact_name: string;
    messages: {
        body: string;
        timestamp: string;
        channel: "email" | "call" | "whatsapp" | "note" | "meeting" | "calendar";
        id: string;
        direction: "outbound" | "inbound";
        to: string[];
        from: string;
        metadata: Record<string, unknown>;
        subject?: string | undefined;
        status?: "sent" | "failed" | "completed" | "delivered" | "scheduled" | "read" | undefined;
        source_id?: string | undefined;
    }[];
    follow_ups: {
        type: "email" | "call" | "whatsapp" | "meeting";
        action: string;
        status: "pending" | "sent" | "completed" | "cancelled";
        id: string;
        scheduled_at: string;
        auto_trigger: boolean;
        triggered_by?: string | undefined;
    }[];
    last_activity: string;
    company_id?: string | undefined;
    contact_email?: string | undefined;
    contact_whatsapp?: string | undefined;
    company_name?: string | undefined;
    last_outbound?: string | undefined;
    last_inbound?: string | undefined;
    next_scheduled?: string | undefined;
    clickup_task_id?: string | undefined;
}, {
    id: string;
    contact_id: string;
    contact_name: string;
    messages: {
        body: string;
        timestamp: string;
        channel: "email" | "call" | "whatsapp" | "note" | "meeting" | "calendar";
        id: string;
        direction: "outbound" | "inbound";
        to: string[];
        from: string;
        subject?: string | undefined;
        status?: "sent" | "failed" | "completed" | "delivered" | "scheduled" | "read" | undefined;
        metadata?: Record<string, unknown> | undefined;
        source_id?: string | undefined;
    }[];
    last_activity: string;
    status?: "active" | "stale" | "resolved" | "blocked" | undefined;
    purpose?: "legal" | "partner" | "vendor" | "fundraising" | "general" | undefined;
    company_id?: string | undefined;
    tags?: string[] | undefined;
    contact_email?: string | undefined;
    contact_whatsapp?: string | undefined;
    company_name?: string | undefined;
    follow_ups?: {
        type: "email" | "call" | "whatsapp" | "meeting";
        action: string;
        id: string;
        scheduled_at: string;
        status?: "pending" | "sent" | "completed" | "cancelled" | undefined;
        triggered_by?: string | undefined;
        auto_trigger?: boolean | undefined;
    }[] | undefined;
    last_outbound?: string | undefined;
    last_inbound?: string | undefined;
    next_scheduled?: string | undefined;
    clickup_task_id?: string | undefined;
}>;
export declare const ThreadRegistrySchema: z.ZodObject<{
    version: z.ZodString;
    generated_at: z.ZodString;
    threads: z.ZodArray<z.ZodObject<{
        id: z.ZodString;
        contact_id: z.ZodString;
        contact_name: z.ZodString;
        contact_email: z.ZodOptional<z.ZodString>;
        contact_whatsapp: z.ZodOptional<z.ZodString>;
        company_id: z.ZodOptional<z.ZodString>;
        company_name: z.ZodOptional<z.ZodString>;
        purpose: z.ZodDefault<z.ZodEnum<["fundraising", "legal", "vendor", "partner", "general"]>>;
        messages: z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            channel: z.ZodEnum<["email", "whatsapp", "calendar", "call", "meeting", "note"]>;
            direction: z.ZodEnum<["inbound", "outbound"]>;
            timestamp: z.ZodString;
            subject: z.ZodOptional<z.ZodString>;
            body: z.ZodString;
            from: z.ZodString;
            to: z.ZodArray<z.ZodString, "many">;
            status: z.ZodOptional<z.ZodEnum<["sent", "delivered", "read", "failed", "scheduled", "completed"]>>;
            source_id: z.ZodOptional<z.ZodString>;
            metadata: z.ZodDefault<z.ZodRecord<z.ZodString, z.ZodUnknown>>;
        }, "strip", z.ZodTypeAny, {
            body: string;
            timestamp: string;
            channel: "email" | "call" | "whatsapp" | "note" | "meeting" | "calendar";
            id: string;
            direction: "outbound" | "inbound";
            to: string[];
            from: string;
            metadata: Record<string, unknown>;
            subject?: string | undefined;
            status?: "sent" | "failed" | "completed" | "delivered" | "scheduled" | "read" | undefined;
            source_id?: string | undefined;
        }, {
            body: string;
            timestamp: string;
            channel: "email" | "call" | "whatsapp" | "note" | "meeting" | "calendar";
            id: string;
            direction: "outbound" | "inbound";
            to: string[];
            from: string;
            subject?: string | undefined;
            status?: "sent" | "failed" | "completed" | "delivered" | "scheduled" | "read" | undefined;
            metadata?: Record<string, unknown> | undefined;
            source_id?: string | undefined;
        }>, "many">;
        follow_ups: z.ZodDefault<z.ZodArray<z.ZodObject<{
            id: z.ZodString;
            type: z.ZodEnum<["email", "whatsapp", "call", "meeting"]>;
            scheduled_at: z.ZodString;
            action: z.ZodString;
            status: z.ZodDefault<z.ZodEnum<["pending", "sent", "completed", "cancelled"]>>;
            triggered_by: z.ZodOptional<z.ZodString>;
            auto_trigger: z.ZodDefault<z.ZodBoolean>;
        }, "strip", z.ZodTypeAny, {
            type: "email" | "call" | "whatsapp" | "meeting";
            action: string;
            status: "pending" | "sent" | "completed" | "cancelled";
            id: string;
            scheduled_at: string;
            auto_trigger: boolean;
            triggered_by?: string | undefined;
        }, {
            type: "email" | "call" | "whatsapp" | "meeting";
            action: string;
            id: string;
            scheduled_at: string;
            status?: "pending" | "sent" | "completed" | "cancelled" | undefined;
            triggered_by?: string | undefined;
            auto_trigger?: boolean | undefined;
        }>, "many">>;
        last_activity: z.ZodString;
        last_outbound: z.ZodOptional<z.ZodString>;
        last_inbound: z.ZodOptional<z.ZodString>;
        next_scheduled: z.ZodOptional<z.ZodString>;
        status: z.ZodDefault<z.ZodEnum<["active", "stale", "resolved", "blocked"]>>;
        tags: z.ZodDefault<z.ZodArray<z.ZodString, "many">>;
        clickup_task_id: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        status: "active" | "stale" | "resolved" | "blocked";
        purpose: "legal" | "partner" | "vendor" | "fundraising" | "general";
        id: string;
        tags: string[];
        contact_id: string;
        contact_name: string;
        messages: {
            body: string;
            timestamp: string;
            channel: "email" | "call" | "whatsapp" | "note" | "meeting" | "calendar";
            id: string;
            direction: "outbound" | "inbound";
            to: string[];
            from: string;
            metadata: Record<string, unknown>;
            subject?: string | undefined;
            status?: "sent" | "failed" | "completed" | "delivered" | "scheduled" | "read" | undefined;
            source_id?: string | undefined;
        }[];
        follow_ups: {
            type: "email" | "call" | "whatsapp" | "meeting";
            action: string;
            status: "pending" | "sent" | "completed" | "cancelled";
            id: string;
            scheduled_at: string;
            auto_trigger: boolean;
            triggered_by?: string | undefined;
        }[];
        last_activity: string;
        company_id?: string | undefined;
        contact_email?: string | undefined;
        contact_whatsapp?: string | undefined;
        company_name?: string | undefined;
        last_outbound?: string | undefined;
        last_inbound?: string | undefined;
        next_scheduled?: string | undefined;
        clickup_task_id?: string | undefined;
    }, {
        id: string;
        contact_id: string;
        contact_name: string;
        messages: {
            body: string;
            timestamp: string;
            channel: "email" | "call" | "whatsapp" | "note" | "meeting" | "calendar";
            id: string;
            direction: "outbound" | "inbound";
            to: string[];
            from: string;
            subject?: string | undefined;
            status?: "sent" | "failed" | "completed" | "delivered" | "scheduled" | "read" | undefined;
            metadata?: Record<string, unknown> | undefined;
            source_id?: string | undefined;
        }[];
        last_activity: string;
        status?: "active" | "stale" | "resolved" | "blocked" | undefined;
        purpose?: "legal" | "partner" | "vendor" | "fundraising" | "general" | undefined;
        company_id?: string | undefined;
        tags?: string[] | undefined;
        contact_email?: string | undefined;
        contact_whatsapp?: string | undefined;
        company_name?: string | undefined;
        follow_ups?: {
            type: "email" | "call" | "whatsapp" | "meeting";
            action: string;
            id: string;
            scheduled_at: string;
            status?: "pending" | "sent" | "completed" | "cancelled" | undefined;
            triggered_by?: string | undefined;
            auto_trigger?: boolean | undefined;
        }[] | undefined;
        last_outbound?: string | undefined;
        last_inbound?: string | undefined;
        next_scheduled?: string | undefined;
        clickup_task_id?: string | undefined;
    }>, "many">;
}, "strip", z.ZodTypeAny, {
    threads: {
        status: "active" | "stale" | "resolved" | "blocked";
        purpose: "legal" | "partner" | "vendor" | "fundraising" | "general";
        id: string;
        tags: string[];
        contact_id: string;
        contact_name: string;
        messages: {
            body: string;
            timestamp: string;
            channel: "email" | "call" | "whatsapp" | "note" | "meeting" | "calendar";
            id: string;
            direction: "outbound" | "inbound";
            to: string[];
            from: string;
            metadata: Record<string, unknown>;
            subject?: string | undefined;
            status?: "sent" | "failed" | "completed" | "delivered" | "scheduled" | "read" | undefined;
            source_id?: string | undefined;
        }[];
        follow_ups: {
            type: "email" | "call" | "whatsapp" | "meeting";
            action: string;
            status: "pending" | "sent" | "completed" | "cancelled";
            id: string;
            scheduled_at: string;
            auto_trigger: boolean;
            triggered_by?: string | undefined;
        }[];
        last_activity: string;
        company_id?: string | undefined;
        contact_email?: string | undefined;
        contact_whatsapp?: string | undefined;
        company_name?: string | undefined;
        last_outbound?: string | undefined;
        last_inbound?: string | undefined;
        next_scheduled?: string | undefined;
        clickup_task_id?: string | undefined;
    }[];
    version: string;
    generated_at: string;
}, {
    threads: {
        id: string;
        contact_id: string;
        contact_name: string;
        messages: {
            body: string;
            timestamp: string;
            channel: "email" | "call" | "whatsapp" | "note" | "meeting" | "calendar";
            id: string;
            direction: "outbound" | "inbound";
            to: string[];
            from: string;
            subject?: string | undefined;
            status?: "sent" | "failed" | "completed" | "delivered" | "scheduled" | "read" | undefined;
            metadata?: Record<string, unknown> | undefined;
            source_id?: string | undefined;
        }[];
        last_activity: string;
        status?: "active" | "stale" | "resolved" | "blocked" | undefined;
        purpose?: "legal" | "partner" | "vendor" | "fundraising" | "general" | undefined;
        company_id?: string | undefined;
        tags?: string[] | undefined;
        contact_email?: string | undefined;
        contact_whatsapp?: string | undefined;
        company_name?: string | undefined;
        follow_ups?: {
            type: "email" | "call" | "whatsapp" | "meeting";
            action: string;
            id: string;
            scheduled_at: string;
            status?: "pending" | "sent" | "completed" | "cancelled" | undefined;
            triggered_by?: string | undefined;
            auto_trigger?: boolean | undefined;
        }[] | undefined;
        last_outbound?: string | undefined;
        last_inbound?: string | undefined;
        next_scheduled?: string | undefined;
        clickup_task_id?: string | undefined;
    }[];
    version: string;
    generated_at: string;
}>;
export type ThreadMessage = z.infer<typeof ThreadMessageSchema>;
export type ThreadFollowUp = z.infer<typeof ThreadFollowUpSchema>;
export type Thread = z.infer<typeof ThreadSchema>;
export type ThreadRegistry = z.infer<typeof ThreadRegistrySchema>;
//# sourceMappingURL=thread.d.ts.map